### ISSUE TITLE
Documentation : README.md vs GitHub Wiki?

### ISSUE THREAD

**Issue by thatfrankdev** [spektrumgeeks/Spk.Common#11]
We should add documentation for all utilities made available.

- Global README.md file?
- Per-namespace README.md?
- Github Wiki feature?

**Comment by gabrielrobert** [comment]
I would say per-namespace README.md. This library will cover so many different concerns, global readme is definitively not an option IMHO.

**Comment by thatfrankdev** [comment]
![image](https://user-images.githubusercontent.com/9736003/32121374-63922f66-bb2a-11e7-8f3b-47b85013fb1e.png)

Also, README.md might be better than Wiki as it is more portable.
