### ISSUE TITLE
Editor config

### ISSUE THREAD

**Issue by gabrielrobert** [spektrumgeeks/Spk.Common#2]
We need a way to use the same code formatting without using any Resharper / VS files.

Of course, we need `.editorconfig`.

**Comment by thatfrankdev** [comment]
Great idea. Two things to remember here, on top of my head :
1. Include an install.ps1 script to deal with the existing .editorconfig file in the target project, if any. (Replace, merge, abort)
2. Make sure not to set these configs as root

**Comment by gabrielrobert** [comment]
@thatfrankdev I think there is a misunderstanding here. This issue is targeting this repository to ensure the uniformity of the whole `Spk.Common` codebase.

But yeah, it's also a good idea to bring a new package, let's say `Spk.Common.EditorConfig` that upon installation call the `install.ps1` file and import configurations to a given repository. It would be neat.

**Comment by thatfrankdev** [comment]
@gabrielrobert Makes a lot more sense

**Comment by gabrielrobert** [comment]
#3 There we go @thatfrankdev!

**Comment by gabrielrobert** [comment]
Solved by #3
