### ISSUE TITLE
Method request: String.Split by string

### ISSUE THREAD

**Issue by gabrielrobert** [spektrumgeeks/Spk.Common#20]
.NET framework does not provide any method to split a string by another string. Proper implementation should look like this:

```csharp
public static string[] Split(this string str, string separator)
{
    return str.Split(new string[1]{ separator }, StringSplitOptions.None);
}
```

Could be used like this:

```csharp
"Hello///how////are///you".Split("///");
```

**Comment by thatfrankdev** [comment]
Sure that'd be cool. However I would keep StringSplitOptions as a parameter. Fixing it to None takes away some flexibility.

**Comment by gabrielrobert** [comment]
There we go @thatfrankdev -> pull-request #21
