### ISSUE TITLE
CollectionSynchronization - Default MatchPredicate is overkill and illogical

### ISSUE THREAD

**Issue by thatfrankdev** [spektrumgeeks/Spk.Common#30]
[This](https://github.com/spektrumgeeks/Spk.Common/blob/master/src/Spk.Common.Helpers/Collection/CollectionSynchronization.cs#L28) is dumb. A case where a.Equals(b) is true, and b.Equals(a) is false, is completely illogical and should never happen. Moreover, perf is suffering cause all non matching elements are evaluated twice. Yuck.

Tests covering that line are insane and should be removed too.

**Comment by MarcAndreJean** [comment]
Actually `a.Equals(b) || b.Equals(a)` make sense if you have object with their Object.Equals() function overrided.

E.g.:
```Class Alpha { 
    string foo { get; set; } 
}
Class Beta : Alpha { 
    override bool Equals(object obj) { 
        if (obj is Alpha casted) return Equals(casted);
        else return ReferenceEquals(this, obj);
    }
}```
Note that by default if the current instance is a reference type, the Equals(Object) method tests for reference equality.
Thereby, if we have =>
```var test1 = new Alpha { foo = "test" }
var test2 = new Beta { foo = "test" }```
test1.Equals(test2) will be false (by reference comparaison)
test2.Equals(test1) will be true (overrided Equals)

Soo ur `a.Equals(b) || b.Equals(a)` will return true.
The question is now, do we want this?

**Comment by gabrielrobert** [comment]
I think we can close it. @MarcAndreJean nailed it.

Onay for you @thatfrankdev?

**Comment by thatfrankdev** [comment]
Sorry, totally forgot to answer.

So yeah @MarcAndreJean, excellent explanation, and that is precisely what I had in mind when I developed it at first. The tests also validate those weird cases.

But! When you think about it, isn't it illogical to develop to different classes that do not agree on their equality? If A says it is equal to B, B should feel the same towards A. I can't think of any case where that would work like that.

What do you think?

**Comment by thatfrankdev** [comment]
On the other hand, since this is a lib and we can't know how it will be used, maybe it is safer to keep it as it is... 🤔
